### ISSUE TITLE
Allow more robust handling of simultaneous PATCH request operations.

### ISSUE THREAD

**Issue by kahammond** [Kentico/kontent-management-sdk-js#22]
### Motivation

When performing a PATCH request, such as [modifying a Taxonomy Group](https://docs.kontent.ai/reference/management-api-v2#operation/modify-a-taxonomy-group), simultaneous actions in the Payload must be able to succeed, or else none of them are successful. For example, here is a taxonomy group in my sample project:
![image](https://user-images.githubusercontent.com/34716170/87992481-61175880-cab6-11ea-8979-caeff5ac7e00.png)

I perform a PATCH request (modifyTaxonomy()) that has a payload with the exact same structure as the payload in the example from the above documentation. It's actions, in order, are:
1. Replace the taxonomy group name.
2. Replace the taxonomy group codename.
3. Replace the contents of the _First Term_ taxonomy term.
4. Remove the Unused Taxonomy Term.
5. Add a new taxonomy term into the _Second-level Taxonomy Term_. (Added from step 3.)

All of these steps are successful when the script is run:
![image](https://user-images.githubusercontent.com/34716170/87993770-5d390580-cab9-11ea-86ed-bdd4a9c41d86.png)

Then, in Kontent, I manually reset the category back to image one. However, I do not create _Unused Taxonomy Term_ again. If I run the same script, nothing changes. The three preceding Replace actions are not successfully run, and neither is the AddInto action afterwards. The script will not be successful unless I either add the _Unused Taxonomy Term_, or I remove the Remove action from the script.

### Proposed solution

It would be great if there was a way to check the payload for actions that do not need to be performed; while still allowing the rest of the payload's actions to run successfully. This could help in testing larger payloads. Even more so if you wanted to add and test one action at a time, or insert actions between other actions. In other words, I want to perform steps 1-5, but I would build the payload one action at a time. 1, 1-2, 1-3, 1-4, 1-5. Between each addition, you would not need to reset the Taxonomy item in order for all of the actions to work.

**Comment by kahammond** [comment]
It looks like a developer is investigating errors that came from my project due to the failed PATCH requests. I will update here if there is any new information.

**Comment by Enngage** [comment]
hey @kahammond, I'm not entirely sure I understand what the sdk should do or implement. Can you be more concrete? 

One idea that comes to my mind is that you expect SDK to first `GET` an object from REST API and then either continue the action or not. Is this understanding correct?

**Comment by Enngage** [comment]
Closing as it is not clear what should be done.
