### ISSUE TITLE
Update Item Docs Unclear or Broken

### ISSUE THREAD

**Issue by hjfitz** [Kentico/kontent-management-sdk-js#25]
### Brief bug description

Updating a kontent item via the management API appears to be broken (or undocumented?)

### Repro steps

Use the following code:

```js
const resp = await client
  .updateContentItem()
  .byItemId('<my item id>')
  .withData({
    title: '<my item title>',
    body: '<a new body>', // the field in kontent that I want to update
  })
  .promise()
```

### Expected behavior

The `body` field in the payload should be reflected in kontent
### Test environment

 - Platform/OS: Darwin Harrys-MBP 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
 - Browser Firefox
 - Version 80.0.1

### Additional context

N/A

### Screenshots

Console log of resp.debug.response -

![image](https://user-images.githubusercontent.com/6014476/93350906-02115e00-f831-11ea-9495-7b39fa329bb6.png)

**Comment by hjfitz** [comment]
Was looking at the wrong docs - for future, what I thought i wanted to do lives here: https://docs.kontent.ai/reference/management-api-v2#operation/upsert-a-language-variant

Getting a new error: 
```"Cannot deserialize the current JSON object (e.g. {\"name\":\"value\"}) into type 'System.Collections.Generic.IEnumerable`1[Kentico.Draft.API.ContentManagementApi.Models.V2.Variants.Request.ContentItemElementRequestModel]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.

To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.

Path 'elements.elements', line 1, position 24."
```

**Comment by Enngage** [comment]
Hi,

The correct syntax should be

```
.withElements([{
                element: {
                    codename: 'x',
                },
                value: ''
            }])
```

Can you try that? Are you using some IDE such as Visual studio code? We are shipping types so it should show you intellisense + warnings (if you are using typescript) if you use incorrect type variables.

**Comment by hjfitz** [comment]
Hey! Thanks for the response -  I found out how to do this by searching GitHub too -- https://github.com/brianjcarroll8/Gatsby/blob/7e83aced6b5c9fc421fd8f3b67b77269a6b59f09/benchmarks/source-kontent/update-article.js

I'm using JavaScript + Vim right now. The Vim setup clearly needs some more config.

Cheers!
