### ISSUE TITLE
Wrong URL and method for modifyContentType()

### ISSUE THREAD

**Issue by michaelwindell26** [Kentico/kontent-management-sdk-js#27]
### Brief bug description

Trying to update a content type using the code below attempts to call the incorrect URL with the wrong method.

```js
client
  .modifyContentType()
  .byTypeCodename(...)
  .withData(...)
```

The [docs](https://docs.kontent.ai/reference/management-api-v2#operation/modify-a-content-type) show the full url as `https://manage.kontent.ai/v2/projects/{project_id}/types/{type_identifier}` and it should be a `PATCH`

However, it is calling `https://manage.kontent.ai/v2/projects/{project_id}/types` as a `POST` resulting in error:

**Codename ‘{codename}’ is not unique.**

**Comment by Enngage** [comment]
Hey @michaelwindell26,

I haven't been able to reproduce this on latest version of the sdk. I've actually been able to successfully use `modifyContentType` to remove an element with following code: 

```typescript
client.modifyContentType()
    .byTypeCodename('actor')
    .withData([{
        op: 'remove',
        path: '/elements/codename:last_name'
     ])
     .toObservable()
     .subscribe();
```

Can you update to latest version if you haven't already or provide me with more information as to how to reproduce this?
