### ISSUE TITLE
Collection is not set when creating new content item using upsertContentItem

### ISSUE THREAD

**Issue by jonasb** [Kentico/kontent-management-sdk-js#31]
### Brief bug description

When creating new content item using `upsertContentItem` providing a collection id, the collection isn't set when creating a new content item. Instead the content item is created with the default collection. I need to make an additional `upsertContentItem` call for the collection id to 'stick'.

### Repro steps

```js
    const contentItemResult = await client
        .upsertContentItem()
        .byItemExternalId(externalId)
        .withData({
            name,
            type: { codename: typeCodename },
            collection: { id: collectionId },
        })
        .toObservable()
        .toPromise()

    console.log(contentItemResult.data.collection.id, collectionId)
```

Workaround by making another upsert:

```js
    const fixUpsertResult = await client
        .upsertContentItem()
        .byItemExternalId(externalId)
        .withData({
            name,
            collection: { id: collectionId },
        })
        .toObservable()
        .toPromise()
```

### Expected behavior

Expect the collection id provided in the initial `upsertContentItem` call to stick, instead the result is the default collection ('00000000-0000-0000-0000-000000000000').

### Test environment

 - Platform/OS: MacOS
 - Browser: Node
 - Version: v14.14.0

**Comment by Enngage** [comment]
Hi @jonasb,

Sorry for late response. This was actually an issue with the MAPI and a fix for that will be deployed within 2 weeks.
