### ISSUE TITLE
No Full SDK Documentation?

### ISSUE THREAD

**Issue by hjfitz** [Kentico/kontent-management-sdk-js#32]
### Motivation

There is no full Management SDK documentation like there is with the [Delivery SDK](https://github.com/Kentico/kontent-delivery-sdk-js/blob/master/DOCS.md)

### Proposed solution

Create full SDK docs

### Additional context

-

**Comment by Enngage** [comment]
Hi @hjfitz ,

Sorry for late response. We are planning on adding full documentation here as well in upcoming months (we have to first refactor core & delivery sdks which will also affect this sdk). 

The documentation for most endpoint is however available on docs.kontent when you select "Javascript" samples such as here: https://docs.kontent.ai/reference/management-api-v2#operation/add-a-content-item

**Comment by cshort-lp** [comment]
> we have to first refactor core & delivery sdks which will also affect this sdk

Hello, is the refactor complete yet? I'm worried that I will invest a significant amount of time in building tools around the management SDK and then have to change it after a refactor.

**Comment by Enngage** [comment]
@cshort-lp yes, we released new major version earlier this week. The API changes are pretty simple, it's basically just removing rxjs and observables from the code so there should be no problems adopting this code.

With that said, the main readme now contains basic scenario to serve as a "tutorial" and I'm not planning on documenting every single method as there are just too many and would become self defeating. 

This sdk is published with Typescript typings so you should see all available methods, props & comments with your IDE.

**Comment by hjfitz** [comment]
>I'm not planning on documenting every single method

Is typedoc available/hosted?

**Comment by Enngage** [comment]
@hjfitz not anymore. I hosted it some time ago, but nobody used it so I removed it from the repos. I can probably revisit this and test it again and see if it improved in some way and discuss within team if it makes sense for us to host it. 

All javascript samples are however still available in our main API reference docs  - https://docs.kontent.ai/reference/management-api-v2
