### ISSUE TITLE
Inconsistent encoding of content ids

### ISSUE THREAD

**Issue by owain68** [Kentico/kontent-management-sdk-js#34]
### Brief bug description

My id's have a `#` in the external-id (emanating from the recommended SingleTable design pattern for AWS DynamoDB).  These content items are now unobtainable using the management API

### Repro steps

1. Create a content item with an external id with a `#` the value using Rest.

```
curl --location --request POST 'https://{{$project_id}}/items' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer {{$api_token}}' \
--data-raw '{
    "name": "deleteMe",
    "type": {
        "codename": "tag"
    },
    "external_id": "TAG#A"
}'
```

2. Try to access the ContentItemVariant using the sdk.

```javascript
const externalId = 'TYPE#A'
const safeId = externalId.split('#').join('%23')
const response = await client.viewLanguageVariant().byItemExternalId(safeId).byLanguageId(consts.KONTENT_DEFAULT_LANGUAGE).toPromise()
```

3.  It is impossible not to get a 404 item not found since the `%` of `%23` is encoded again.

4. These tests fail

`test-browser/language-variants/view-language-variants.spec.ts`
```javascript
    it(`urls should be encoded correctly`, () => {
        const externalIdWithPoundUrlWithIdLanguage = cmLiveClient.viewLanguageVariant().byItemExternalId('TYPE#A').byLanguageId('xLanguageId').getUrl();
        const externalIdWithEncodedPoundUrlWithIdLanguage = cmLiveClient.viewLanguageVariant().byItemExternalId('TYPE%23A').byLanguageId('xLanguageId').getUrl();
        expect(externalIdWithPoundUrlWithIdLanguage).toEqual(`https://manage.kontent.ai/v2/projects/${testProjectId}/items/TYPE%23A/XItemExternal/variants/xLanguageId`);
        expect(externalIdWithEncodedPoundUrlWithIdLanguage).toEqual(`https://manage.kontent.ai/v2/projects/${testProjectId}/items/TYPE%23A/XItemExternal/variants/xLanguageId`);
    });
```

### Expected behavior

as per test conditions but these are the actual results
```
externalIdWithPoundUrlWithIdLanguage: https://manage.kontent.ai/v2/projects/b259760f-81c5-013a-05e7-69efb4b954e5/items/external-id/TYPE#A/variants/xLanguageId
externalIdWithEncodedPoundUrlWithIdLanguage: https://manage.kontent.ai/v2/projects/b259760f-81c5-013a-05e7-69efb4b954e5/items/external-id/TYPE%2523A/variants/xLanguageId
```
### Test environment

node

### Additional context

Available on kontent support chat.  I think that if urlencoding was working properly then it would naturally encode the `#` and the call should not need to make it safe.

```javascript
const stringA = 'TYPE#'
const encodedStringA = encodeURIComponent(stringA)
const reEncodeStringA = encodeURIComponent(encodedStringA)

console.log('stringA', stringA)
console.log('encodeStringA', encodedStringA)
console.log('reEncodeStringA', reEncodeStringA)

==> stringA TYPE#
==> encodeStringA TYPE%23
==> reEncodeStringA TYPE%2523

```

**Comment by owain68** [comment]
As the SDK is just a wrapper around the endpoints (with a bit of model support) then I can categorically state that this an SDK problem as the following command works with `#` replaced by `%23`.

```shell
curl --location --request GET 'https://manage.kontent.ai/v2/projects/$project_id/items/external-id/TAG%23A' \
--header 'Authorization: Bearer $api_token'
```
returns 

```json
{
    "id": "7ccede88-cf86-5661-8305-d46d31c4a566",
    "name": "deleteMe",
    "codename": "deleteme",
    "type": {
        "id": "ddda1ff0-cee4-5512-b0d0-f7af56181c49"
    },
    "collection": {
        "id": "00000000-0000-0000-0000-000000000000"
    },
    "sitemap_locations": [],
    "external_id": "TAG#A",
    "last_modified": "2021-01-28T09:35:10.2417316Z"
}
```

**Comment by owain68** [comment]
In discussion with the support team, we have come up with, I hope, a temporary workaround.  It is a bit untidy but it does the job.

```javascript
  fetchLanguageVariant: async (id) => {
    const safeId = id.split('#').join('%23')
    const url = client.viewLanguageVariant().byItemExternalId(safeId).byLanguageId(consts.KONTENT_DEFAULT_LANGUAGE).getUrl()
    const cleanUrl = url.split('%25').join('%')
    const vLV = await client.viewLanguageVariant()
      .byItemExternalId(safeId)
      .byLanguageCodename(consts.KONTENT_DEFAULT_LANGUAGE)
      .withUrl(cleanUrl)
      .toPromise()
      .catch((error) => {
        console.info(error)
      })
    return vLV?.data
  }
```

**Comment by Enngage** [comment]
The solution provided above with the use of  ```withUrl``` is the correct one. 

The hash (#) sign the external id is not encoded because it is a valid URL character (well, depending on location). There are bunch of other characters that will get encoded too. 

At the moment I don't think its the responsibility of SDK to determine what valid URL character should or shouldn't be encoded. I'm not ruling out a possibility of changing this in the future, but right now the `withUrl` is the way to go in scenarios where you need to have full control over the URL.

We will have to better document this alongside other aspects of the SDK which is in our backlog ;)
