### ISSUE TITLE
Error Propagation

### ISSUE THREAD

**Issue by mattnield** [Kentico/kontent-management-sdk-js#41]
### Brief bug description

I'm using the Management SDK with the Kontent CLI in order to script the creation of my content model. I've based this on the [content migration biolerplate][1] using the JS rather than the TS example. The issues is that exceptions are not propagated. 

At the moment I have a work around courtesy of @Simply007 using hte debugger, but longer term we need the error to be raised back up to the user.

### Repro steps

1. Script a new JS import to create a simple type. Run this migration and check that the type is created. Script simiarl tothe below:
```
const migration = {
    order: 2,
    run: async(apiClient) => {
        await apiClient
            .addContentType()
            .withData(BrandTypeData)
            .toPromise();
    }
};

const BrandTypeData = (builder) => {
    return {
        name: 'Brand',
        codename: 'brand',
        elements: [
            builder.textElement({
                name: 'Name',
                codename: 'name',
                type: 'text'
            })
        ]
    };
};

module.exports = migration;
```

2. Modify `status.json` to remove that file from the log.
3. Re-run the migration. This should fail because the type already exists.
4. Error show to the user will be similar to:

```
An error occurred while running migration: 06_grr_init_createRestaurantContentType.js see the output from running the script.
Message: call.mapError is not a function
Execution of the "06_grr_init_createRestaurantContentType.js" migration was not successful, stopping...
```

### Expected behavior

Error message is displayed to the user, allowing them to correct any issues.

### Test environment

 - Platform/OS: Windows 10 Pro (20H2)
 - Node: v14.15.4
 - npm: 6.14.10
 - @kontent/kontent-cli: 0.0.10
 - @kontnet/kontent-management: 0.4.10
 - rxjs: 7.0.0

### Additional context

As mentions, based on the [boilerplate migrations][1] using the JS example.

### Screenshots

![image](https://user-images.githubusercontent.com/11173358/117790564-6316f780-b241-11eb-8b32-3b81f85fd6e2.png)

[1]: https://github.com/Kentico/kontent-migrations-boilerplate

**Comment by Simply007** [comment]
In a nutshell:

Error handling using `Observable` is described in the repository:
* https://github.com/Kentico/kontent-management-sdk-js#making-the-first-request

But using `Promise`  and error handling is not and using the try catch block does not propagate inner error to the outer scope, so following code:

```js
try {
        await apiClient
            .addContentType()
            .withData(BrandTypeData)
            .toPromise();
} catch(error) {
  console.log(error); // Error does not contain the information about the actual error returned from REST API 
}
```

**Comment by Enngage** [comment]
I'm closing this as it doesn't seem to be related to this sdk. The Observables are replaced by Promises in next version of this sdk and there is a note regarding error handling in new readme.

**Comment by Simply007** [comment]
@Enngage - and will it `error` variable in catch block contain information about [Errors from Kontent reposnses](https://docs.kontent.ai/reference/management-api-v2#section/Errors)?

Because currently it does not.

**Comment by Enngage** [comment]
@Simply007 yeah, it should - at least in the next version. This is what I tested: 

```typescript
        try {
            const testClient = new ManagementClient({
                projectId: 'y',
                apiKey: 'x'
            });

            await testClient.viewContentType().byTypeCodename('invalid-type').toPromise();

        } catch (err) {
            if (err instanceof SharedModels.ContentManagementBaseKontentError) {
                const message = err.message;
                const errorCode = err.errorCode;
            }
        }
```

Both `message`  and `errorCode` was properly parsed from the Kontent response.

**Comment by Simply007** [comment]
Cool - the current version does not propagate it. If the new version (currently still in alpha) does, I guess it is fine.
