### ISSUE TITLE
ContentItemElement should extend IContentItemElementContract generics

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-management-sdk-js#42]
https://github.com/Kentico/kontent-management-sdk-js/blob/2fc3cfacda01d9412f3c1e8e5a061b6904fcf8c1/lib/models/elements/elements.models.ts#L26

I guess this element should base the generics on `IContentItemElementContract` right?

**Comment by Enngage** [comment]
@Simply007 Yeah, it should ;) I've fixed it in the next version branch, thank you!
