### ISSUE TITLE
Unable to set `content_group` for elements based on Content Type Snippets

### ISSUE THREAD

**Issue by mattnield** [Kentico/kontent-management-sdk-js#44]
I'm trying to script my models using TypeScript (migrating form JavaScript). When adding a Content Type Snippet using the following code I get an error:
```
builder.snippetElement({
    snippet: {
        codename: "metadata"
    },
    type: 'snippet',
    content_group: { 
        codename: 'seo'
    }
})
```
The error I see is:
> Argument of type '{ snippet: { codename: string; }; type: "snippet"; content_group: { codename: string; }; }' is not assignable to parameter of type 'ISnippetInType'.
> Object literal may only specify known properties, and 'content_group' does not exist in type 'ISnippetInType'.ts(2345)

Using vanilla JS for the import worked fine for this, but in TypeScript there is a limitation. Looks like it is in the [definition for `ISnippetInType][1], where the following line would help:
```
content_group?: SharedContracts.IReferenceObjectContract;
```
Is there a reason for it missing, or is it an oversight?

[1]: https://github.com/Kentico/kontent-management-sdk-js/blob/2fc3cfacda01d9412f3c1e8e5a061b6904fcf8c1/lib/models/content-types/content-type-elements.builder.ts#L38

**Comment by Enngage** [comment]
Thank you, this is indeed missing from both sdk and our documentation (https://docs.kontent.ai/reference/management-api-v2#operation/add-a-content-type). 

Its now fixed in vnext of sdk and will soon be updated in docs as well.
