### ISSUE TITLE
Cannot set `codename` for Content Group

### ISSUE THREAD

**Issue by mattnield** [Kentico/kontent-management-sdk-js#45]
I'm trying to script my models using TypeScript (migrating form JavaScript). When adding a new Content Type using the following code I get an error:
```
const BrandTypeData = (builder: ContentTypeElementsBuilder
    ): ContentTypeModels.IAddContentTypeData => {
    return {
        name: 'Brand',
        codename: 'brand',
        content_groups: [{
                codename: 'general',
                name: 'General'
            },
            {
                codename: 'seo',
                name: 'SEO'
            }
        ],
        elements: [...
```
The error I see is:
> Type '{ codename: string; name: string; }' is not assignable to type 'IAddContentTypeContentGroup'.
> Object literal may only specify known properties, and 'codename' does not exist in type 'IAddContentTypeContentGroup'.ts(2322)

I appreciate my codename here would match the default, but in some cases I wanted to be super-sure what I was getting so that I could add element to the type knowing I have the correct codename. Using vanilla JS for the import worked fine for this, but in TypeScript there is a limitation which looks like it is in the [definition for `IAddContentTypeContentGroup][1]

Is there a reason for it missing, or is it an oversight?

[1]: https://github.com/Kentico/kontent-management-sdk-js/blob/914e022a58adb2c7b4e68980041087c75b459235/lib/models/content-types/content-type.models.ts#L60

**Comment by Enngage** [comment]
Fixed in vnext
