### ISSUE TITLE
Different types for element on content type when retrieving and creating content types

### ISSUE THREAD

**Issue by Bondza** [Kentico/kontent-management-sdk-js#46]
I am using the management client with TypeScript to copy content types between projects. I noticed that the types returned for elements on a content type does not match the types when creating an element on a content type.

The types used to create elements can be found [here](https://github.com/Kentico/kontent-management-sdk-js/blob/master/lib/models/content-types/content-type-elements.builder.ts). But when I retrieve a content type using the SDK the returned element type is [`ElementContracts.IContentTypeElementContract`](https://github.com/Kentico/kontent-management-sdk-js/blob/2fc3cfacda01d9412f3c1e8e5a061b6904fcf8c1/lib/contracts/content-type-contracts.ts#L11). I was expecting the element types to match what the [docs](https://docs.kontent.ai/reference/management-api-v2#section/Asset-element-in-type) say here for example.

It would be very helpful if the element type when retrieving a content type had multiple different types or interfaces for each element type. Also it could be useful if the element types used [discriminated unions](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions).

Am I using the SDK with TypeScript the wrong way or is there a problem with the types here?

**Comment by Enngage** [comment]
Hi @Bondza,

Yeah, the interfaces for elements in GET responses are very basic. This is from the time the API did not provide anything else. You can still access all data in your response, you just have to cast is as 'any' or use your own interface. 

I'll keep this open and will work on this when possible.

**Comment by Enngage** [comment]
Types are added to vnext and will be part of the next major release.

**Comment by Bondza** [comment]
That's great! Do you know when these changes will be released to npm?

**Comment by Enngage** [comment]
They already are :) All preview versions are released under next tag - https://www.npmjs.com/package/@kentico/kontent-management/v/1.0.0-next.5
