### ISSUE TITLE
Add support for term limitations in Taxonomy element

### ISSUE THREAD

**Issue by KristianJakubik** [Kentico/kontent-management-sdk-js#48]
### Motivation

Add support for limiting terms in Taxonomy element in Management API v2

### Proposed solution

Enhance response/request models with the properties for term limitation

### Additional context

* Although docs has not been updated yet, until then we might take inspiration from [Asset element in type](https://docs.kontent.ai/reference/management-api-v2#section/Asset-element-in-type)
![image](https://user-images.githubusercontent.com/28342527/124912256-04c28700-dfee-11eb-9ffa-13704dea9e7c.png)
* Taxonomy Element property for term limitation should look like this:
 ``` 
  term_count_limit: {
    "value": number,
    "condition": string (Enum: "at_most", "exactly", "at_least")
  }
 ```
* Endpoints: 
  * `POST v2/projects/{project_id}/types `
  * `GET  v2/projects/{project_id}/types`
  * `GET v2/projects/{project_id}/types/{type_identifier}`
  * `PATCH v2/projects/{project_id}/types/{type_identifier} `
  * `DEL v2/projects/{project_id}/types/{type_identifier}`
  * Same for content type snippets
* Response:
```
{
    "id": "2d11938a-07ed-45c2-91e9-2635ee27939a",
    "codename": "test_2d11938",
    "last_modified": "2021-07-08T18:01:13.5754404Z",
    "name": "Test",
    "content_groups": [],
    "elements": [
        {
            "guidelines": null,
            "taxonomy_group": {
                "id": "41f013c2-d3a6-4fbf-af1f-466f6326e5c4"
            },
            "is_required": false,
            "term_count_limit": {
                "value": 5,
                "condition": "at_least"
            },
            "type": "taxonomy",
            "id": "08a922b4-8ba4-4f37-8144-f71e69e81a56",
            "codename": "untitled_taxonomy_group"
        }
    ]
}
```

**Comment by Enngage** [comment]
Will be included in next release
