### ISSUE TITLE
Add environment to ProjectInformationModel

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/kontent-management-sdk-js#49]
### Motivation

The Management API now returns environment name for [project information ](https://docs.kontent.ai/reference/management-api-v2#tag/Project-information) the type should be updated to include this information

### Proposed solution

Update the `ProjectInformationModel` to include environment

**Comment by Enngage** [comment]
@ChristopherJennings thanks! I've updated SDK accordingly.
