### ISSUE TITLE
Publishing with CM requires date in the future

### ISSUE THREAD

**Issue by Enngage** [Kentico/kontent-management-sdk-js#5]
### Brief bug description

When attempting to use `publishOrScheduleLanguageVariant()`, I cannot publish now or at the next scheduled publish

### Repro steps

A few cases
1. Use `publishOrScheduleLanguageVariant` without `.withData` -> type error -- is not a function
2. Use `publishOrScheduleLanguageVariant` with empty `.withData` -> 404 -- "The provided value is not a valid date."
3. Use `publishOrScheduleLanguageVariant` with date in the past in `.withData` -> 400 -> "The provided date value needs to be in the future."

### Expected behavior

For each case, I expect:
1. The ability not to include data 
2. The ability not to specific a time
3. The ability to provide a time in the past and get a 204, as described in the documentation: https://developer.kenticocloud.com/reference#content-management-api-v2-publish-language-variant

### Test environment

Firefox

**Comment by CollierCZ** [comment]
The [documentation](https://docs.kontent.ai/reference/content-management-api-v2#operation/publish-or-schedule-a-language-variant) has been changed to reflect that you can't provide a time in the past and get a 204. The options for the endpoint are include data for scheduling or not include data for immediate publishing.

**Comment by alexcanessa** [comment]
> The [documentation](https://docs.kontent.ai/reference/content-management-api-v2#operation/publish-or-schedule-a-language-variant) has been changed to reflect that you can't provide a time in the past and get a 204. The options for the endpoint are include data for scheduling or not include data for immediate publishing.

If you don't pass anything (e.g. `withData({})` then it will complains:

```
The provided value is not a valid date. Specify a value in the ISO-8601 formatted date-time format.
```

**Comment by Enngage** [comment]
@alexcanessa maybe you could try using `withoutData();` method instead ;)
