### ISSUE TITLE
Add support for Subpages element

### ISSUE THREAD

**Issue by Neytus** [Kentico/kontent-management-sdk-js#51]
Based on the information provided, add SDK support for a new element type: `"subpages"`

Related Jira task: https://kentico.atlassian.net/browse/KCL-7804
Expected latest release date: 10.11.2021

**Comment by Enngage** [comment]
Fixed by https://github.com/Kentico/kontent-management-sdk-js/commit/5713d8f5ae75023040dd2d0b60dc7d7b77c0755f
