### ISSUE TITLE
Unable to stop errors from being logged/Errors thrown are different values

### ISSUE THREAD

**Issue by hjfitz** [Kentico/kontent-management-sdk-js#53]
### Brief bug description

When catching an error with the management client, the axios error is printed to the console.

The error caught also has a different value to that thrown; I am unable to reach, too.

Given the following block, which is attempting to programatically add new items to the content model:

![image](https://user-images.githubusercontent.com/6014476/139827411-30ac0c33-51c7-4f81-91e5-54b4618b79fd.png)

This error is still printed to the terminal:

![image](https://user-images.githubusercontent.com/6014476/139827513-4819b9a4-293f-49b5-bab8-93f84a16f425.png)

The static method `handleKontentError` looks like this:

![image](https://user-images.githubusercontent.com/6014476/139827600-3a84c57c-678d-4cdc-88c3-41d30bf259fc.png)

So I'm confident that this isn't the issue.

Logging and stringifying the error in console gives us a different type to the one printed by the management client:

![image](https://user-images.githubusercontent.com/6014476/139827714-4cbcd335-0cbc-4f0f-9e76-38ecad532f07.png)

### Repro steps

1. call `ManagementClient#addContentType.withData.toPromise` with an invalid payload
2. Catch the error
3. Observe that it's still printed to the terminal
4. Observe that you have a different error

### Expected behavior

What the correct behavior is?

### Test environment

 - Platform/OS: Node 15.5.1; Typescript 4.4.4; @kentico/kontent-management@1.5.0
 - Browser n/a

### Additional context

Have tried `toPromise().catch()`, but the behaviour still exists.

### Screenshots

See above

**Comment by Enngage** [comment]
Hey @hjfitz ,

The error is logged to console by `@kentico/kontent-core` when HTTP request fails (see https://github.com/Kentico/kontent-core-js/blob/master/lib/http/http.functions.ts#L267) 

The error you get in CM SDK should be the same as it's propagated without any changes. In my testing, the error was indeed the same.  The only difference should be the sentence that says how many times the error was retried. 

Is logging the error to the console causing you some issues?

**Comment by hjfitz** [comment]
Hey @Enngage 

Cheers for the response! I'm not sure why I'm not getting a different error - this looks like it must be something on my side.

I'd love it if we could toggle that error on/off: we' provide an internal CLI that propagates content model changes/updates - in the case that the request fails, we'd love to be able to fail silently.

**Comment by Enngage** [comment]
There was actually a toggle in previous version, but it was removed in recent refactoring. I can bring it back though ;) Shouldn't be too difficult, so I'll release a new version with toggle this week (probably)

**Comment by Enngage** [comment]
@hjfitz, it wasn't very difficult to implement, so I've released a new update `1.6.0` which enables you to turn the logging off. 

To do so, use this when initializing management client: 

```typescript
const managementClient = new ManagementClient({
   apiKey: 'x',
   projectId: 'y',
   httpService: new HttpService({
      logErrorsToConsole: false
   })
});
```

Hope it helps ;)

**Comment by hjfitz** [comment]
My hero, thank you!

We've got a lovely output in our consoles now ;) 

![image](https://user-images.githubusercontent.com/6014476/139876051-79c4cd1d-7385-4108-8db1-8f209b87a13c.png)

**Comment by mattnield** [comment]
Hi, joining the party late here. This is something I've seen over the past few months that I've bee involved in scripting. Great to see that we can turn it off @Enngage . Perhaps though it could be turned off by default?

In _every_ instance where I have exceptions I usually have my own way of dealing with them based on whether I expect them or not and don't really wan't the axios response dumped to the console.
