### ISSUE TITLE
Extend custom regex validation with validation message

### ISSUE THREAD

**Issue by IvanKiral** [Kentico/kontent-management-sdk-js#55]
### Motivation

Validation Regex is being extended with custom validation messages. The issue should add property of the validation message into the SDK models.

### Proposed solution

* [ ] Extend content-type-element.models.ts with validation message property

### Additional context

Related issue: https://kentico.atlassian.net/jira/software/c/projects/KCL/boards/543?modal=detail&selectedIssue=KCL-7870

**Comment by IvanKiral** [comment]
I would like to keep this issue

**Comment by Enngage** [comment]
closed by https://github.com/Kentico/kontent-management-sdk-js/pull/56
