### ISSUE TITLE
Add support for project roles

### ISSUE THREAD

**Issue by zbynekh** [Kentico/kontent-management-sdk-js#57]
### Motivation

We have added new endpoints to the Management API for project roles and we would like it to be covered in the SDK.
(!) Going to be released in the first half of January 22.

### Proposed solution

The SDK should include the functionality of the new endpoints for roles:

- get all roles
- get role by identifier

### Additional context

See Docs preview for more detailed info.

The endpoints that were added:
- `GET /{projectId}/roles`
  - returns all roles in the project, no pagination
  - sample response:
```yaml
{
  "roles":[
    {
      "id":"7dedb656-aef7-40ae-8158-98bbf3542f4a",
      "name":"Project manager",
      "codename":"project-manager"
    },
    {
      "id":"ee483b59-5a24-4010-b277-ae224c34bc71",
      "name":"Custom role"
    }
  ]
}
```

- `GET /{project_id}/roles/{role_identifier}`
  - returns role by its identifier (id or codename)
  - sample response:
```yaml
{
  "id":"7dedb656-aef7-40ae-8158-98bbf3542f4a",
  "name":"Project manager",
  "codename":"project-manager"
}
```

**Comment by milan009** [comment]
Released on 2022-01-12
