### ISSUE TITLE
Add support for elements in Asset entity

### ISSUE THREAD

**Issue by Suzii** [Kentico/kontent-management-sdk-js#71]
### Motivation

The feature "asset tagging", internally represented as the presence of Taxonomy elements in the Asset entity was introduced to the UI a while ago and now has made its way to the MAPI as well. Now is the time to add support to MAPI SDKs.

### Proposed solution

Introduce new property `Elements` to the Asset entity and make it work. The idea for the API to be exactly the same as elements in language variants, although Asset currently only supports Taxonomy elements that are non-localizable. The API and SDKs, however, should be "generic" enough so that any type element can be easily supported in the future.

### Additional context

The feature will be released ~7.3.2022 together with the docs.

The `Elements` property is being returned from the GET endpoints and is optionally accepted in the POST/PUT endpoints. Only elements that are present during insert/update/upsert will be modified.

**Comment by Suzii** [comment]
PR for .NET SDK from which it should be obvious, how the contract changes: https://github.com/Kentico/kontent-management-sdk-net/pull/145
All MAPI endpoints working with the `Asset` entity now return/accept a new `elements` property in JSON. The contract works exactly the same as for Language Variants, but assets have more endpoints for manipulating the entity: Create, Update, Upsert.

**Comment by Simcsa** [comment]
Code samples in the KK docs project updated to include JS example in advance (TWs know they should wait with publishing till this SDK is implemented). If the setup of the newly added taxonomies differs from it, please update also the code samples.

. https://github.com/KenticoDocs/kontent-docs-samples/pull/45

**Comment by Enngage** [comment]
Implemented using the builder as @Simcsa suggested in code samples ;)
