### ISSUE TITLE
Requests withoutData include header Content-Type: application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by KristianJakubik** [Kentico/kontent-management-sdk-js#72]
### Brief bug description

Sending PUT/POST request with empty body (`.withoutData()`) sends content-type header: "application/x-www-form-urlencoded".
Some servers/endpoints might return 415 Unsupported Media Type for this type of requests.
This is a different approach as .NET sdk has. .NET sdk for empty body requests doesn't send content-type header at all, which is IMHO correct. Postman has a similar approach.

### Repro steps

```
 client.publishLanguageVariant()
  .byItemId('00000000-0000-0000-0000-000000000000')
  .byLanguageId('00000000-0000-0000-0000-000000000000')
    .withoutData()
    .toPromise()
    .then((response) => {
        console.log(response)
        },
    (error) => {
        console.log(error)
    });
```
In the console, you should be able to see the headers of the requests and there is Content-Type header
![image](https://user-images.githubusercontent.com/28342527/156812755-747db047-f671-4a78-a744-c0276503538f.png)

### Expected behavior

The client is not sending a content-type header for requests that don't include the body.

### Test environment

 - node: v16.10.0; Windows 10

**Comment by Enngage** [comment]
Hey @KristianJakubik,

Was this a problem with our API or does it only affect cases when using proxy server? I've never had any problems with this, but it's definitely good to know so I'll have a look at this.

**Comment by Enngage** [comment]
Hi @KristianJakubik, 

I've looked at code and we are not setting `Content-Type: application/x-www-form-urlencoded` anywhere. Rather, this appears to be set by Axios automatically as a default header (https://github.com/axios/axios/blob/e52e4dbb575fc8bd9cb7d2f5306f30ee82b40b4d/lib/defaults/index.js#L9). I'm really not sure why they do this, but maybe this is intentional and has some (to me unknown) reasons. I will not be changing or overriding their behavior unless we discover some problem with this.

**Comment by KristianJakubik** [comment]
We had some issues with it because we don't typically support requests/endpoints in `application/x-www-form-urlencoded`
format. But because of these types of requests, we had to add explicit logic for fixing the BE, as it caused a breaking change for people using the SDK.
I wanted to point out that the behavior among the SDKs are different. 
The next step might be that the header we are sending is `application/json`, IMHO this would be a more feasible approach towards our BE, but as I said it had to be handled on our BE explicitly anyway, so it might not have priority.
