### ISSUE TITLE
Add support for multiple workflows

### ISSUE THREAD

**Issue by RadoslavK** [Kentico/kontent-management-sdk-js#74]
### Motivation

We have added multiple workflows to MAPI and slightly adjusted even some existing endpoints to reflect the new feature.

### Proposed solution

- Deprecate change workflow step action, endpoint: `PUT /projects/{project_id}/items/{item_identifier}/variants/{language_identifier}/workflow/{workflow_step_identifier}`

- Workflow response model is common for all endpoints that return the workflow entity. It is a little bit different from the insert request model.
 ```
{
    id, // UUID string (internal ID)
    name, // string
    codename, // string
    steps: [
      {
        id, // UUID string (internal ID)
        name, // string
        codename, // string
        color, // string, possible/accepted values: https://kentico.atlassian.net/browse/CTC-1565?focusedCommentId=481083
        transitions_to: [
          {
             step, // ManageApiReferenceModel
          }
        ],
        role_ids, // array of UUID strings (internal IDs)
      }
    ],
    scopes: [
      {
        content_types, // array of ManageApiReferenceModel (can be an internal ID or codename)
      }
    ],
    published_step: {
      id, // UUID string (internal ID)
      name, // string
      codename, // string
      create_new_version_role_ids, // array of UUID strings (internal IDs)
      unpublish_role_ids, // array of UUID strings (internal IDs)
    },
    archived_step: {
      id, // UUID string (internal ID)
      name, // string
      codename, // string
      role_ids, // array of UUID strings (internal IDs)
    }
  } 
``` 
- Get all workflows
  - add endpoint: `GET /projects/{project_id}/workflows`
  - returns an array of workflows
- Insert workflow
  - add endpoint: `POST /projects/{project_id}/workflows`
  - returns the inserted workflow
  - request model
```
{
  name, // string
  codename, // string - optional
  steps: [
    {
      name, // string
      codename, // string
      color, // string, possible/accepted values: https://kentico.atlassian.net/browse/CTC-1565?focusedCommentId=481083
      transitions_to: [ // cannot be empty
        { 
          step, // ManageApiReferenceModel
        }
      ],
      role_ids, // array of UUID strings (cannot be empty)
    }
  ],
  scopes: [ (0 or 1 items)
    {
      content_types, // array of ManageApiReferenceModel
    }
  ],
  published_step: {
    create_new_version_role_ids, // array of UUID strings (cannot be empty)
    unpublish_role_ids, // array of UUID strings (cannot be empty)
  },
  archived_step: {
    role_ids, // array of UUID strings (cannot be empty)
  }
}
```
- Update workflow
  - add endpoint: `PUT /projects/{project_id}/workflows/<workflow_identifier>`
  - request model is the same as for Insert
  - returns the updated workflow
- Delete workflow
  - add endpoint : `DELETE /projects/{project_id}/worfklows/<workflow_identifier>` 
  - does not return anything
- Change workflow + step of variant directly
  - add endpoint: `PUT /projects/{project_id}>/items/<item_identifier>}/variants/<language_identifier>/change-workflow`
  - does not return anything
  - The request model contains only the required `workflow` property of the same type as `workflow` in variant upsert. See model below.
- Change workflow + step via variant upsert
  - adjust endpoints: `PUT /projects/{project_id}/items/<item_identifier>/variants/<language_identifier>` 
  - extend the request model with an optional `workflow` property. The internal properties are both required.
  - extend the content item variant response model (returned from all endpoints) with the `workflow` property. The shape is the same as the one from the request model but it will always be present. It duplicates the information of the `workflow_step` property so that one can be made deprecated.
 ```
elements: [], // Already present
workflow: {
  workflow_identifier, // ManageApiReferenceModel, workflow internal id or codename
  step_identifier // ManageApiReferenceModel, workflow step internal id or codename
}
```

### Additional context

We do not support external ids in the ManageApiReferenceModel for workflows and workflow steps. We simply ignore them.
This feature will be released at the end of March.
[](url)

**Comment by Simply007** [comment]
Did you mean to close this one @RadoslavK?

**Comment by RadoslavK** [comment]
@Simply007 No, I thought I was just closing a comment or something :D

**Comment by jankalfus** [comment]
Updated scopes in the request model by changing `content_type_ids` property to `content_types`. We were probably missing here 
the latest changes that were made.

**Comment by RadoslavK** [comment]
`Update` endpoint requirements have changed and it is the only endpoint not live. It will be finalized and live by the next release 13.4.

**Comment by Enngage** [comment]
New endpoints are implemented (https://github.com/Kentico/kontent-management-sdk-js/tree/workflow-updates) and old methods are marked as deprecated. Waiting for official release before publishing new SDK Version.
