### ISSUE TITLE
Asset Folders Integration into SDKs

### ISSUE THREAD

**Issue by owain68** [Kentico/kontent-management-sdk-js#8]
### Motivation

There is a REST endpoint but no equivalent in the SDK for managing asset folders.

### Proposed solution

Add https://manage.kontent.ai/v2/projects/{project_id}/folders to the SDKs

**Comment by Enngage** [comment]
Implemented via https://github.com/Kentico/kontent-management-sdk-js/commit/b35b08d6391f0ae6cbfb988499ec6bbe05213a0e

Released under `0.3.0`
